### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by fommil** [cage433/maker#96]
1. transitive resources (and add a "test" phase so that main doesn't depend on test stuff)
2. ~~a `maker-mode` similar to [`sbt-mode`](https://github.com/hvesalai/sbt-mode/). In particular, equivalents of `sbt-command`/`sbt-run-previous-command` and `next-error`~~
3. plugin architecture (or at least in-built ports of some of the top plugins such as `scalariform`, `scoverage`, `sbt-updates`, `sbt-dependency-graph`, `scapegoat`/`wartremover`/`scalastyle`
4. self-downloader (i.e. so `maker` becomes a script like `paulp`'s `sbt`)
5. really easy sonatype/travis-ci SNAPSHOT publishing and manual gpg central publishing
6. windows support: no more reliance on calling out to the shell
7. type `console` (or `repl`) => start a repl with the project classpath all in scope (ensime can do this for us as a workaround)

and to ease the migration from sbt projects:
1. `sbt-maker` plugin to export an sbt project layout to maker
2. maker support for the `sbt`/`maven` project layout

competitive advantages to aim for:
1. faster transitive resolution
2. cleaner, more practical API (actually already there)
3. expose the presentation compiler over a socket (this may be an upstream requirement on zinc)

**Comment by cage433** [comment]
Transitive resources now available - uses Aether, dependencies described in the project file using a syntax similar to SBT
Sonatype publishing works - see the function`publish` in Maker.scala.
